# Default values for bigquery-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: measurementlab/prometheus-bigquery-exporter
  tag: latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
queryConfigmapName: billing-insights-query
credentialsSecretName: billing-insights
project_id: company-billing-insights
queryConfigmapName: billing-insights-query
queryInterval: 5m
queryFile: billing.sql
securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 0
serviceAccount:
  create: false
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 9348

ingress:
  enabled: false
  annotations: {}
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  serviceMonitor:
    prometheusServiceMonitorLabel: feat-billing-insights
    enabled: true
    scrapeTimeout: 30s
    honorTimestamps: false
    honorLabels: false
    interval: 1m
