apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab-pipeline-monitoring.fullname" . }}
  labels:
    {{- include "gitlab-pipeline-monitoring.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gitlab-pipeline-monitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gitlab-pipeline-monitoring.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitlab-pipeline-monitoring.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: gitlab
            value: '{{ .Values.gitlab }}'
          - name: groups
            value: '{{  join "," .Values.gitlabGroups }}'
          - name: cron_schedule
            value: '{{ .Values.gitlabScrapeCronSchedule }}'
          - name: gitlab_query_interval_seconds
            value: '{{ .Values.gitlabQueryIntervalSeconds }}'
          - name: gateway
            value: '{{ .Values.pushgateway }}'
          - name: token
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tokenSecret }}
                key: token
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
