{{- if .Values.nfs.server }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "file-sync-to-gcp.fullname" . }}-nfs"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 80Gi
  volumeName: "{{ include "file-sync-to-gcp.fullname" . }}-nfs"
{{- end }}